name: tokenbridge-contracts

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
      - run: npm install
        if: ${{ !steps.npm-cache.outputs.cache-hit }}
      - run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
      - run: npm install
        if: ${{ !steps.npm-cache.outputs.cache-hit }}
      - run: npm run test
  gasreport:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
      - run: npm install
        if: ${{ !steps.npm-cache.outputs.cache-hit }}
      - run: npm run test:gasreport:ci
        env:
          CC_SECRET: ${{ secrets.CC_SECRET }}
  coverage:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
      - run: npm install
        if: ${{ !steps.npm-cache.outputs.cache-hit }}
      - run: npm run coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
  publish:
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v2
      - if: startsWith(github.ref, 'refs/tags')
        run: echo "DOCKER_TAGS=${GITHUB_REF#refs/tags/},latest" >> $GITHUB_ENV
      - if: startsWith(github.ref, 'refs/heads')
        run: echo "DOCKER_TAGS=${GITHUB_REF#refs/heads/}-${GITHUB_SHA::8}" >> $GITHUB_ENV
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: poanetwork/tokenbridge-contracts
          always_pull: true
          tags: ${{ env.DOCKER_TAGS }}
